//! DPDK kernel bypass abstraction layer.
//!
//! This module provides a trait-based abstraction over DPDK's
//! Environment Abstraction Layer (EAL) for kernel-bypass packet I/O.
//!
//! In production, this wraps `rte_eth_rx_burst()` / `rte_eth_tx_burst()`.
//! For testing and non-DPDK environments, a `MockDpdkPort` is provided.

use bytes::Bytes;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

use super::types::{FeedError, FeedResult};

/// Maximum number of packets in a RX burst.
pub const MAX_BURST_SIZE: usize = 32;

/// A DPDK port abstraction for kernel-bypass packet reception.
pub trait DpdkPort: Send + Sync {
    /// Receive a burst of packets from the NIC.
    ///
    /// # Returns
    /// A vector of raw packet buffers (zero-copy from NIC memory).
    fn rx_burst(&self) -> Vec<Bytes>;

    /// Get the port ID.
    fn port_id(&self) -> u16;

    /// Check if the port is active.
    fn is_active(&self) -> bool;

    /// Downcast to concrete type (for testing).
    fn as_any(&self) -> &dyn std::any::Any;
}

/// Builder for DPDK port configuration.
pub struct DpdkConfig {
    pub port_id: u16,
    pub num_rx_queues: u16,
    pub num_tx_queues: u16,
    pub rx_desc: u16,
    pub tx_desc: u16,
    pub mbuf_pool_size: u16,
}

impl Default for DpdkConfig {
    fn default() -> Self {
        Self {
            port_id: 0,
            num_rx_queues: 1,
            num_tx_queues: 1,
            rx_desc: 4096,
            tx_desc: 4096,
            mbuf_pool_size: 65535,
        }
    }
}

impl DpdkConfig {
    pub fn new(port_id: u16) -> Self {
        Self {
            port_id,
            ..Default::default()
        }
    }
}

/// A production DPDK port using the real DPDK EAL.
///
/// This is a stub that would link against `libdpdk` in a real deployment.
/// The actual FFI bindings to `rte_eal_init`, `rte_eth_dev_configure`, etc.
/// would be generated by `bindgen` in a build script.
pub struct RealDpdkPort {
    config: DpdkConfig,
    active: Arc<AtomicBool>,
}

impl RealDpdkPort {
    /// Initialize DPDK EAL and configure the port.
    ///
    /// # Safety
    /// This function calls into DPDK C library via FFI.
    pub fn new(config: DpdkConfig) -> FeedResult<Self> {
        // In production, this would:
        // 1. Call rte_eal_init() with appropriate arguments
        // 2. Configure the Ethernet port with rte_eth_dev_configure()
        // 3. Set up RX/TX queues with rte_eth_rx_queue_setup()
        // 4. Create mbuf pool with rte_pktmbuf_pool_create()
        // 5. Start the device with rte_eth_dev_start()
        //
        // For now, we validate the config and return a stub.
        if config.num_rx_queues == 0 || config.num_tx_queues == 0 {
            return Err(FeedError::DpdkPortConfig(
                "at least one RX and TX queue required".to_string(),
            ));
        }
        if config.rx_desc < 64 || config.tx_desc < 64 {
            return Err(FeedError::DpdkPortConfig(
                "descriptor rings must be at least 64 entries".to_string(),
            ));
        }

        Ok(Self {
            config,
            active: Arc::new(AtomicBool::new(true)),
        })
    }
}

impl DpdkPort for RealDpdkPort {
    #[inline]
    fn rx_burst(&self) -> Vec<Bytes> {
        // In production:
        // let mut mbufs: [*mut rte_mbuf; MAX_BURST_SIZE] = unsafe { std::mem::zeroed() };
        // let nb_rx = unsafe { rte_eth_rx_burst(self.port_id, 0, mbufs.as_mut_ptr(), MAX_BURST_SIZE as u16) };
        // Convert each mbuf to Bytes (zero-copy from mbuf's data buffer)
        Vec::new()
    }

    fn port_id(&self) -> u16 {
        self.config.port_id
    }

    fn is_active(&self) -> bool {
        self.active.load(Ordering::Relaxed)
    }

    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
}

/// A mock DPDK port for testing and non-DPDK environments.
///
/// Simulates packet reception from an in-memory ring buffer.
pub struct MockDpdkPort {
    port_id: u16,
    active: Arc<AtomicBool>,
    packet_source: crossbeam_channel::Sender<Bytes>,
    packet_receiver: crossbeam_channel::Receiver<Bytes>,
}

impl MockDpdkPort {
    pub fn new(port_id: u16) -> Self {
        let (tx, rx) = crossbeam_channel::unbounded();
        Self {
            port_id,
            active: Arc::new(AtomicBool::new(true)),
            packet_source: tx,
            packet_receiver: rx,
        }
    }

    /// Inject a packet into the mock port (for testing).
    pub fn inject_packet(&self, data: Bytes) -> Result<(), FeedError> {
        self.packet_source
            .send(data)
            .map_err(|_| FeedError::ChannelSend)
    }

    /// Inject multiple packets (for testing).
    pub fn inject_packets(&self, packets: Vec<Bytes>) -> Result<(), FeedError> {
        for pkt in packets {
            self.inject_packet(pkt)?;
        }
        Ok(())
    }
}

impl DpdkPort for MockDpdkPort {
    #[inline]
    fn rx_burst(&self) -> Vec<Bytes> {
        let mut packets = Vec::with_capacity(MAX_BURST_SIZE);
        while packets.len() < MAX_BURST_SIZE {
            match self.packet_receiver.try_recv() {
                Ok(pkt) => packets.push(pkt),
                Err(_) => break,
            }
        }
        packets
    }

    fn port_id(&self) -> u16 {
        self.port_id
    }

    fn is_active(&self) -> bool {
        self.active.load(Ordering::Relaxed)
    }

    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::feed_handler::protocol::{HEADER_SIZE, PacketParser};

    #[test]
    fn test_mock_port_rx_burst() {
        let port = MockDpdkPort::new(0);
        let pkt = Bytes::from_static(&[0u8; HEADER_SIZE]);
        port.inject_packet(pkt.clone()).unwrap();

        let burst = port.rx_burst();
        assert_eq!(burst.len(), 1);
        assert_eq!(burst[0].len(), HEADER_SIZE);
    }

    #[test]
    fn test_mock_port_burst_limit() {
        let port = MockDpdkPort::new(0);
        let pkt = Bytes::from_static(&[0u8; HEADER_SIZE]);
        for _ in 0..(MAX_BURST_SIZE + 10) {
            port.inject_packet(pkt.clone()).unwrap();
        }

        let burst = port.rx_burst();
        assert_eq!(burst.len(), MAX_BURST_SIZE);
    }

    #[test]
    fn test_real_dpdk_config_validation() {
        let config = DpdkConfig {
            num_rx_queues: 0,
            ..Default::default()
        };
        let result = RealDpdkPort::new(config);
        assert!(matches!(result, Err(FeedError::DpdkPortConfig(_))));
    }

    #[test]
    fn test_mock_port_parse_injected() {
        let port = MockDpdkPort::new(0);

        // Build a valid packet
        let mut buf = vec![0u8; HEADER_SIZE];
        buf[0..8].copy_from_slice(&42u64.to_le_bytes());
        buf[8..16].copy_from_slice(&1000i64.to_le_bytes());
        buf[16..24].copy_from_slice(&500u64.to_le_bytes());
        buf[24] = 0; // bid
        buf[28..32].copy_from_slice(&12345u32.to_le_bytes());
        buf[32..36].copy_from_slice(&1u32.to_le_bytes());
        buf[36..40].copy_from_slice(&0u32.to_le_bytes());

        port.inject_packet(Bytes::from(buf)).unwrap();

        let burst = port.rx_burst();
        assert_eq!(burst.len(), 1);

        let event = PacketParser::parse(&burst[0], 0).unwrap();
        assert_eq!(event.instrument_id, 42);
        assert_eq!(event.price, 1000);
    }
}
