#!/bin/bash
# Trivy security scanner for ULL infrastructure
# Usage: ./security/trivy/trivy-scan.sh [target] [type]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

TARGET="${1:-all}"
TYPE="${2:-all}"
OUTPUT_DIR="${PROJECT_ROOT}/security/reports"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

mkdir -p "${OUTPUT_DIR}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if trivy is installed
check_trivy() {
    if ! command -v trivy &> /dev/null; then
        log_error "Trivy is not installed. Install it first:"
        echo "  brew install trivy"
        echo "  or"
        echo "  curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin"
        exit 1
    fi
    log_info "Trivy version: $(trivy --version)"
}

# Scan container image
scan_image() {
    local image="$1"
    local report_name="trivy-image-${image//[:\/]/_}-${TIMESTAMP}"

    log_info "Scanning image: ${image}"

    trivy image \
        --severity CRITICAL,HIGH,MEDIUM \
        --format json \
        --output "${OUTPUT_DIR}/${report_name}.json" \
        --scanners vuln,secret,misconfig \
        --ignore-unfixed \
        "${image}" 2>/dev/null || true

    trivy image \
        --severity CRITICAL,HIGH \
        --format table \
        --scanners vuln,secret,misconfig \
        "${image}" 2>/dev/null || true

    log_info "Image scan complete: ${report_name}.json"
}

# Scan filesystem
scan_filesystem() {
    local path="${1:-.}"
    local report_name="trivy-fs-${TIMESTAMP}"

    log_info "Scanning filesystem: ${path}"

    trivy fs \
        --severity CRITICAL,HIGH,MEDIUM \
        --format json \
        --output "${OUTPUT_DIR}/${report_name}.json" \
        --scanners vuln,secret,misconfig \
        --ignore-unfixed \
        "${path}" 2>/dev/null || true

    trivy fs \
        --severity CRITICAL,HIGH \
        --format table \
        --scanners vuln,secret,misconfig \
        "${path}" 2>/dev/null || true

    log_info "Filesystem scan complete: ${report_name}.json"
}

# Scan IaC (Kubernetes manifests, Terraform)
scan_iac() {
    local path="${1:-.}"
    local report_name="trivy-iac-${TIMESTAMP}"

    log_info "Scanning IaC: ${path}"

    trivy config \
        --severity CRITICAL,HIGH,MEDIUM \
        --format json \
        --output "${OUTPUT_DIR}/${report_name}.json" \
        "${path}" 2>/dev/null || true

    trivy config \
        --severity CRITICAL,HIGH \
        --format table \
        "${path}" 2>/dev/null || true

    log_info "IaC scan complete: ${report_name}.json"
}

# Scan Kubernetes cluster
scan_kubernetes() {
    local report_name="trivy-k8s-${TIMESTAMP}"

    log_info "Scanning Kubernetes cluster"

    trivy k8s \
        --severity CRITICAL,HIGH,MEDIUM \
        --format json \
        --output "${OUTPUT_DIR}/${report_name}.json" \
        --scanners vuln,misconfig \
        cluster 2>/dev/null || true

    trivy k8s \
        --severity CRITICAL,HIGH \
        --format table \
        cluster 2>/dev/null || true

    log_info "Kubernetes scan complete: ${report_name}.json"
}

# Generate summary report
generate_summary() {
    local summary_file="${OUTPUT_DIR}/trivy-summary-${TIMESTAMP}.md"

    log_info "Generating summary report: ${summary_file}"

    cat > "${summary_file}" << EOF
# Trivy Security Scan Summary

**Date:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")
**Target:** ${TARGET}
**Type:** ${TYPE}

## Scan Results

| Scan Type | Report File | Status |
|-----------|-------------|--------|
EOF

    for report in "${OUTPUT_DIR}"/trivy-*-${TIMESTAMP}.json; do
        if [ -f "$report" ]; then
            local name=$(basename "$report" .json)
            local vulns=$(jq -r '.Results[]?.Vulnerabilities | length // 0' "$report" 2>/dev/null | awk '{s+=$1} END {print s}')
            local secrets=$(jq -r '.Results[]?.Secrets | length // 0' "$report" 2>/dev/null | awk '{s+=$1} END {print s}')
            local misconfigs=$(jq -r '.Results[]?.Misconfigurations | length // 0' "$report" 2>/dev/null | awk '{s+=$1} END {print s}')

            echo "| ${name} | $(basename "$report") | V:${vulns} S:${secrets} M:${misconfigs} |" >> "${summary_file}"
        fi
    done

    cat >> "${summary_file}" << EOF

## Recommendations

1. Review all CRITICAL and HIGH vulnerabilities immediately
2. Rotate any exposed secrets
3. Fix misconfigurations before deployment
4. Update base images to latest patched versions

## Next Steps

- Review detailed reports in JSON format
- Create tickets for remediation
- Re-scan after fixes

---
*Generated by ULL Trivy Scanner*
EOF

    log_info "Summary report generated: ${summary_file}"
}

# Main execution
main() {
    log_info "Starting Trivy security scan"
    log_info "Target: ${TARGET}"
    log_info "Type: ${TYPE}"

    check_trivy

    case "${TYPE}" in
        image)
            scan_image "${TARGET}"
            ;;
        fs|filesystem)
            scan_filesystem "${TARGET}"
            ;;
        iac)
            scan_iac "${TARGET}"
            ;;
        k8s|kubernetes)
            scan_kubernetes
            ;;
        all)
            scan_filesystem "${PROJECT_ROOT}"
            scan_iac "${PROJECT_ROOT}"
            if command -v kubectl &> /dev/null; then
                scan_kubernetes
            else
                log_warn "kubectl not found, skipping Kubernetes scan"
            fi
            ;;
        *)
            log_error "Unknown scan type: ${TYPE}"
            echo "Usage: $0 [target] [image|fs|iac|k8s|all]"
            exit 1
            ;;
    esac

    generate_summary

    log_info "Scan complete. Reports saved to: ${OUTPUT_DIR}"
}

main "$@"
